### ISSUE TITLE
Buffers are converted to strings

### ISSUE THREAD

**Issue by imnotjames** [nodefluent/kafka-streams#57]
Hi

I'm trying to 

```
let outStream = kafkaStreams.getKStream(null);
await outStream.to({ topic: 'output-topic' });

outStream.writeToStream(Buffer.from([ 1, 2, 3, 4, 5 ]));
```

However, when I am reading the data back in using another stream I end up with a "string" representation of the value.

```
{ topic: 'output-topic',
  value: '\u0001\u0002\u0003\u0004\u0005',
  offset: 8,
  partition: 0,
  highWaterOffset: 9,
  key: null }
```

Am I doing something incorrectly to cause this to happen?  I would like to work with the raw buffer so that I can utilize a custom encoding mechanism.

**Comment by imnotjames** [comment]
Looks like once I switch to the native kafka it corrects this - but maybe it's some config option I've chosen?

**Comment by krystianity** [comment]
Hi @imnotjames working with Buffers is not possible in the pure JS Version (as of now). It is possible to implement that in Sinek (underlying Kafka Client Wrapper though), but currently I am leaning towards calling the pure JS client deprecated in Sinek, as it does not hold up with the feature and performance of the native client implementation based on librdkafka, which is why I am also suggesting it in the quick start doc. 

> We really want to encourage you to always use the native clients if possible.

**Comment by imnotjames** [comment]
Interesting!  I did get that it was strongly encouraged, but I was curious from a few standpoints.  I'm going to poke in the direction of sinek, as well.

Thanks!

**Comment by imnotjames** [comment]
I opened https://github.com/nodefluent/node-sinek/pull/62 to handle this on the sinek side, and as a temporary workaround, I updated my `options` to have the `encoding` and `keyEncoding` set to `buffer` so everything matches the librdkafka consuming.
